services:
  whatsapp:
    image: aldinokemal2104/go-whatsapp-web-multidevice
    restart: always
    ports:
      - "3080"
    volumes:
      - whatsapp:/app/storages
    command:
      - rest
      - --basic-auth=${WA_USER}:${WA_PASSWORD}
      - --port=3080
      - --debug=true
      - --os=Chrome
      - --account-validation=false
    networks:
      - whatsapp-gowhatsappwebmultidevice-wiodwh
    labels:
      - traefik.http.routers.whatsapp-gowhatsappwebmultidevice-wiodwh-1-web.rule=Host(`whatsapp-gowhatsappwebmultidevice-f766f6-46-224-148-239.traefik.me`)
      - traefik.http.routers.whatsapp-gowhatsappwebmultidevice-wiodwh-1-web.entrypoints=web
      - traefik.http.services.whatsapp-gowhatsappwebmultidevice-wiodwh-1-web.loadbalancer.server.port=3080
      - traefik.http.routers.whatsapp-gowhatsappwebmultidevice-wiodwh-1-web.service=whatsapp-gowhatsappwebmultidevice-wiodwh-1-web
      - traefik.enable=true
      - traefik.http.routers.whatsapp-ip.rule=Host(`46.224.148.239`)
      - traefik.http.routers.whatsapp-ip.entrypoints=web
      - traefik.http.routers.whatsapp-ip.service=whatsapp-gowhatsappwebmultidevice-wiodwh-1-web
volumes:
  whatsapp: null
networks:
  whatsapp-gowhatsappwebmultidevice-wiodwh:
    name: whatsapp-gowhatsappwebmultidevice-wiodwh
    external: true
